### PR TITLE
Fix "php-fpm" crash on non-existent host

### PR DESCRIPTION
**Pull request by Shark-vil**
https://github.com/riflowth/skinsystem/issues/119

### CODE REVIEW

**Comment by Shark-vil** [comment]
https://github.com/riflowth/skinsystem/issues/119

**Comment by riflowth** [comment]
Is this PR solve (#119)? I can't test on PHP now.
Thanks for improvement 🙏

**Comment by Shark-vil** [comment]
> Is this PR solve (#119)? I can't test on PHP now. Thanks for improvement 🙏

Yes. I use this solution it now on my server. While there were no more crash.

**Comment by aion1998** [comment]
..我就是遇到这个错误，不光站点，整个服务器都被弄崩溃了

**Comment by AlexProgrammerDE** [comment]
Has been merged in https://github.com/SkinsRestorer/SkinSystem/commit/20f0a067e7f8c94b6438e9ff95f199795d59469d
The PR unfortunately makes a lot of code reformats that are unneeded. I will be adding a style formatter in the future.

**Pull request closed without merging**
